### ISSUE TITLE
bad wiretype error

### ISSUE THREAD

**Issue by indrekj** [bsm/appdash-rb#1]
To replicate:
```
x = Appdash::Client.new(host: '10.200.0.42', port: 7701)
x.span {|s| s.name("request"); s.message("asdf")}
```

Server shows:
```
Read 0 traces from file /tmp/appdash.gob
appdash collector listening on :7701 (plaintext TCP (no security))
appdash HTTP server listening on :7700
CollectorServer[[::]:7701]: 2017/03/01 17:19:06.276853 Client 10.200.0.118:56432: ReadMsg: proto: bad wiretype for field wire.CollectPacket_SpanID.Trace: got wiretype 2, want 1
```

**Comment by dim** [comment]
Sorry, we have not been maintaining this gem for a while. It was written when Appdash API was still not stable. I am happy to revive this project. Could you submit a PR?

**Comment by indrekj** [comment]
Only if you have any suggestions where to look for fixing this issue. I went over the protobuf definition and everything seemed correct.

**Comment by dim** [comment]
Pushed an update, but something is still broken. Looks like it's the server's fault though. I checked appdash to see what's going on, the tests are not passing, there are a bunch of outstanding issues and there have been no commits since November.

**Comment by indrekj** [comment]
Ok, thanks.
